server:
  port: 8080

spring:
  application:
    name: trendzy-ingestion-service

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: trendxee

  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:127.0.0.1:9092}
    admin:
      properties:
        request.timeout.ms: 30000
        default.api.timeout.ms: 30000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        delivery.timeout.ms: 120000
        linger.ms: 1
        batch.size: 16384

scraper:
  instagram:
    session-dir: ${user.home}/.trendzy