server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: trendzy-ingestion-service

  data:
    mongodb:
      uri: ${MONGODB_URI:}
      database: trendxee

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile

  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:127.0.0.1:9092}
    admin:
      properties:
        request.timeout.ms: 30000
        default.api.timeout.ms: 30000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        delivery.timeout.ms: 120000
        linger.ms: 1
        batch.size: 16384

app:
  jwtSecret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  jwtExpirationMs: 86400000
  frontend:
    redirectUri: ${FRONTEND_URL:https://trendxee.com}/auth/callback

scraper:
  instagram:
    session-dir: ${user.home}/.trendzy
